[package]
name = "ctru-sys"
version = "0.4.0"
authors = ["Ronald Kinard <furyhunter600@gmail.com>"]
license = "https://en.wikipedia.org/wiki/Zlib_License"
links = "ctru"
edition = "2021"

[dependencies]
libc = { version = "0.2", default-features = false }
