[package]
name = "ctru-sys"
version = "0.3.0"
authors = ["Ronald Kinard <furyhunter600@gmail.com>"]
license = "https://en.wikipedia.org/wiki/Zlib_License"

[dependencies]
ctr-libc = { path = "../ctr-libc" }
