[package]
name = "std"
version = "0.0.0"
license = "MIT/Apache 2.0"

[dependencies.alloc_system]
path = "../../alloc_system3ds"

[dependencies.ctru-sys]
path = "../ctru-sys"
default-features = false
features = ["stdbuild"]
